### ISSUE TITLE
Additional metrics (+tests)

### ISSUE THREAD

**Issue by simonhkswan** [synthesized-io/insight#61]
For the tests of the new metrics, would be good to follow (you can search this approach too):

- Arrange
- Act
- Assert

Let's have a look at `pytest.fixture`s too.

**Comment by Hebruwu** [comment]
As there are many clustering algorithms, I will be limiting the scope to k-means for now as it is a very popular algorithm, but requires the knowledge of an optimal number of clusters in order to perform optimally
