### ISSUE TITLE
Easily save the results of a synthesis trial to a database including: the metrics and value the dataset the generative model

### ISSUE THREAD

**Issue by simonhkswan** [synthesized-io/insight#70]

**Comment by Hebruwu** [comment]
The database is not getting populated when the eval.py script is run on eval-1 database.

Steps to reproduce:
- Run `docker-compose up -d` in the project directory.
- Open connection to the docker in CLI
- Run eval.py script
- No errors shown
- Optional: run `alembic upgrade head` in /code
- run `psql -h postgres -U postgres`
- use `\dt+` to display all the tables
- We can see that the table size for all except alembic and dataset tables are 0.
